language: generic

sudo: required

after_success: |
  wget -c https://github.com/rust-lang/mdBook/releases/download/v0.3.5/mdbook-v0.3.5-x86_64-unknown-linux-gnu.tar.gz
  tar -vzxf mdbook*.tar.gz
  npm install -g surge
  ./mdbook init --force docs;cp -varf `ls | grep -v docs` docs/src/
  mv -v docs/src/book.toml docs/
  cd docs/
  ../mdbook build
  surge book --token $SURGE_TOKEN
notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOK
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always