[book]
authors = ["Raul Dipeas"]
language = "pt-br"
multilingual = false
src = "src"
title = "XFScripts"

[output.html]
theme = "coal"
default-theme = "coal"
preferred-dark-theme = "coal"
#additional-js = "book.js"
git-repository-url = "https://github.com/rauldipeass/xfscripts"
git-repository-icon = "fa-github"